#!/bin/zsh
# make sure you remove the original files before

# sudo ln -s fstab /etc/fstab # you probably don't want to copy this one!

ln -s ~/ArchConfigs/.zshrc ~/.zshrc
ln -s ~/ArchConfigs/.xinitrc ~/.xinitrc
ln -s ~/ArchConfigs/.Xresources ~/.Xresources
ln -s ~/ArchConfigs/.xbindkeysrc ~/ArchConfigs/.xbindkeysrc
ln -s ~/ArchConfigs/user-dirs.dirs ~/.config/user-dirs.dirs
ln -s ~/ArchConfigs/gtksettings.ini ~/.config/gtk-3.0/settings.ini
ln -s ~/ArchConfigs/gtk.css ~/.config/gtk-3.0/gtk.css

ln -s ~/ArchConfigs/init.el ~/.emacs.d/init.el
ln -s ~/ArchConfigs/myinit.org ~/.emacs.d/myinit.org

ln -s ~/ArchConfigs/cantata.conf ~/.config/cantata/cantata.conf

ln -s ~/ArchConfigs/i3config ~/.config/i3/config
ln -s ~/ArchConfigs/i3status.conf ~/.config/i3status/config

sudo rm /etc/pacman.conf
sudo ln -s ~/ArchConfigs/pacman.conf /etc/pacman.conf

systemctl --user enable emacs.service
systemctl --user start emacs.service
