#!/bin/zsh
# make sure you remove the original files before

# sudo ln -s fstab /etc/fstab # you probably don't want to copy this one!

ln -s ~/ArchConfigs/.zshrc ~/.zshrc
ln -s ~/ArchConfigs/.xinitrc ~/.xinitrc
ln -s ~/ArchConfigs/.Xresources ~/.Xresources
ln -s ~/ArchConfigs/.emacs ~/.emacs
ln -s ~/ArchConfigs/user-dirs.dirs ~/.config/user-dirs.dirs
ln -s ~/ArchConfigs/gtksettings.ini ~/.config/gtk-3.0/settings.ini
ln -s ~/ArchConfigs/gtk.css ~/.config/gtk-3.0/gtk.css

ln -s ~/ArchConfigs/i3config ~/.config/i3/config
ln -s ~/ArchConfigs/i3status.conf ~/.config/i3status/config
