preload = /home/japhir/Pictures/wallpapers/Landscapes/1359330091856.jpg
wallpaper = , /home/japhir/Pictures/wallpapers/Landscapes/1359330091856.jpg
# preload = /home/japhir/Pictures/wallhaven-7j3lve.png
# wallpaper = , /home/japhir/Pictures/wallhaven-7j3lve.png
